import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidenav from "@/app/ui/users/Sidenav";
import { PropsWithChildren } from "react";
import BreadCrumbItemProvider from "@/app/ui/BreadcrumbItemProvider";
import AccountSetting from "../ui/AccountSetting";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "State generator",
  description: "Generated by create next app",
};

export default function layout({ children }: PropsWithChildren) {
  return (
    <div className="flex flex-col h-full">
      <div className="flex justify-between items-center bg-slate-900 text-white">
        <h1 className="text-3xl p-3">Miezaka EURL</h1>
        <AccountSetting />
      </div>
      <div className="flex h-full">
        <Sidenav />
        <main className="flex-1 w-5/6">
          <BreadCrumbItemProvider />
          <div className="px-3 pt-5">{children}</div>
        </main>
      </div>
    </div>
  );
}
